import react from 'react';

export default function Home() {
    return (
        <flexbox>
            <title>Mi portafolio</title>
            <meta name="myportfolioproyect" content="Generated by next app and created by Claudio Chametla" />
            <link rel="icon" href="/favicon.ico" />
        </flexbox>
    );
}
